# Your personal GitHub token
github_token: <token pessoal gerado no link abaixo>
# Read more: https://github.com/blog/1509-personal-api-tokens
# You can generate it here: https://github.com/settings/tokens

# Guest OS timezone
timezone: Europe/London

# Are we need check box updates for every 'vagrant up'?
box_check_update: true

# Virtual machine name
machine_name: src

# Virtual machine IP
ip: 192.168.83.100

# Virtual machine CPU cores number
cpus: 1

# Virtual machine RAM
memory: 2048
